name: demo workflow
on: workflow_dispatch
jobs:
  demojob:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "demo pipeline"
  demoactionjob:
    runs-on: windows-latest
    steps:
      - name: show ip address
        uses: Amadevus/pwsh-script@v2.0.3
        with:
          script: |
            write-host "hello world"
          
  
