name: List Active Pull Requests

on:
  workflow_dispatch:

jobs:
  list_active_prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Active Pull Requests
        id: list_prs
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Fetch the GitHub token from environment variable
          TOKEN=$GH_TOKEN
          REPO_OWNER='saravana4064'
          REPO_NAME='demo-app'

          # Fetch the list of open pull requests using GitHub API
          response=$(curl -sSf -H "Authorization: token $TOKEN" \
                    "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls")

          # Check if curl command was successful
          if [ $? -ne 0 ]; then
            echo "Failed to fetch pull requests from GitHub API."
            exit 1
          fi

          # Check if JSON response contains an array of pull requests
          if ! echo "$response" | jq -e . >/dev/null; then
            echo "Invalid JSON response received from GitHub API."
            exit 1
          fi

          # Parse the JSON response to get the list of pull requests
          active_prs=$(echo "$response" | jq -r '.[] | "\(.number): \(.title) (\(.user.login))"')

          # Check if there are any active pull requests
          if [ -z "$active_prs" ]; then
            echo "No active pull requests found."
          else
            echo "Active Pull Requests:"
            echo "$active_prs"
          fi
